name: Check Disk Space

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  check-disk-space:
    runs-on: self-hosted

    steps:
      - name: Check disk space
        run: df -h /
